version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - webtv:/downloads
      - /tmp/downloads:/tmp/downloads
      - /data/metube:/data
    env_file:
      - docker-compose.env
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.metube.entrypoints=websecure
      - traefik.http.routers.metube.rule=Host(`metube.polaris.video`)
      - traefik.http.routers.metube.tls.certresolver=acme
      - traefik.http.routers.metube.middlewares=authentik@docker
      - traefik.http.services.metube.loadbalancer.server.port=8081

  metube-music:
    image: ghcr.io/alexta69/metube
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - musicvideo:/downloads
      - /tmp/downloads:/tmp/downloads
      - /data/metube-music:/data
    env_file:
      - docker-compose.music.env
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.metube-mv.entrypoints=websecure
      - traefik.http.routers.metube-mv.rule=Host(`metube-mv.polaris.video`)
      - traefik.http.routers.metube-mv.tls.certresolver=acme
      - traefik.http.services.metube-mv.loadbalancer.server.port=8081

volumes:
  webtv:
    driver_opts:
      type: nfs
      o: addr=10.10.0.10,nfsvers=4
      device: :/mnt/data/polaris/webtv
  musicvideo:
    driver_opts:
      type: nfs
      o: addr=10.10.0.10,nfsvers=4
      device: :/mnt/data/content/musicvideo

networks:
  traefik:
    name: traefik
    external: true