file_ids:
- database/pgadmin/docker-compose.env
- infrastructure/authentik/.env
- infrastructure/authentik/docker-compose.authentik.env
- infrastructure/authentik/docker-compose.postgres.env
- infrastructure/authentik/docker-compose.radius.env
- infrastructure/authentik/docker-compose.redis.env
- infrastructure/cloudflareddns/docker-compose.env
- infrastructure/traefik/docker-compose.env
- infrastructure/watchtower/.env
- infrastructure/watchtower/docker-compose.env
- media/downloaders/metube/docker-compose.env
- media/downloaders/sabnzbd/.env
- media/downloaders/sabnzbd/docker-compose.env
- media/indexers/prowlarr/.env
- media/indexers/prowlarr/docker-compose.env
- media/indexers/radarr/.env
- media/indexers/radarr/docker-compose.env
- media/indexers/sonarr/.env
- media/indexers/sonarr/docker-compose.env
- media/servers/ersatz/docker-compose.env
- media/servers/plex/.env
- media/servers/plex/docker-compose.env
- media/utils/overseerr/.env
- media/utils/overseerr/docker-compose.env
- media/utils/tautulli/.env
- media/utils/tautulli/docker-compose.env
- services/coder-v2/docker-compose.coder.env
- services/coder-v2/docker-compose.postgres.env
- services/coder/docker-compose.env
- services/github-runner/docker-compose.tracker.env
- services/pterodactyl/docker-compose.mysql.env
- services/pterodactyl/docker-compose.panel.env
- services/pterodactyl/docker-compose.wings.env
- services/tailscale-golink/docker-compose.env
- services/tailscale-recorder/docker-compose.env
version: "1"
