version: '3.8'

services:
  cloudflareddns:
    image: cr.hotio.dev/hotio/cloudflareddns:latest
    restart: always
    env_file:
      - docker-compose.env
    network_mode: bridge
    volumes:
      - /data/cloudflareddns:/config
