version: '3.8'

services:
  cloudflareddns:
    image: favonia/cloudflare-ddns:latest
    restart: always
    env_file:
      - docker-compose.env
    network_mode: bridge
    labels:
      - com.centurylinklabs.watchtower.enable=true