version: "3.4"
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - 8266:8266
    environment:
      - TZ=America/Los_Angeles
      - PUID=1001
      - PGID=1001
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=Docker
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /data/tdarr/server:/app/server
      - /data/tdarr/configs:/app/configs
      - /data/tdarr/logs:/app/logs
      - movies:/media/movies
      - tv:/media/tv
      - /tmp/transcode:/tmp/transcode
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.tdarr.entrypoints=websecure
      - traefik.http.routers.tdarr.rule=Host(`tdarr.polaris.video`)
      - traefik.http.routers.tdarr.tls.certresolver=acme
      - traefik.http.services.tdarr.loadbalancer.server.port=8265

    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
volumes:
  movies:
    driver_opts:
      type: nfs
      o: addr=10.10.0.10,nfsvers=4
      device: :/mnt/data/polaris/movies
  tv:
    driver_opts:
      type: nfs
      o: addr=10.10.0.10,nfsvers=4
      device: :/mnt/data/polaris/tv

networks:
  traefik:
    name: traefik
    external: true