version: '3.8'

services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      start_period: 10s
      interval: 5s
      retries: 5
      timeout: 2s
    env_file:
      - docker-compose.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/traefik/:/etc/traefik
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik
    labels:
      - com.centurylinklabs.watchtower.monitor-only=true
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.int.zhr.one`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls.certresolver=acme
      - homepage.group=Infrastructure
      - homepage.name=Traefik
      # - homepage.icon=emby.png
      - homepage.href=https://traefik.int.zhr.one/
      - homepage.description=HTTP/TCP reverse proxy for all services
      - homepage.widget.type=traefik
      - homepage.widget.url=https://traefik.int.zhr.one/

networks:
  traefik:
    name: traefik
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/24
          gateway: 172.20.1.254