version: '3.8'

services:
  portainer:
    image: portainer/portainer-ee:latest
    restart: unless-stopped
    # healthcheck:
    #   test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
    #   start_period: 10s
    #   interval: 5s
    #   retries: 5
    #   timeout: 5s
    volumes:
      - /data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.portainer-frontend.entrypoints=websecure
      - traefik.http.routers.portainer-frontend.rule=Host(`portainer.int.zhr.one`)
      - traefik.http.routers.portainer-frontend.tls.certresolver=acme
      - traefik.http.routers.portainer-frontend.service=portainer-frontend
      - traefik.http.services.portainer-frontend.loadbalancer.server.port=9000
      - traefik.http.routers.portainer-edge.entrypoints=websecure
      - traefik.http.routers.portainer-edge.rule=Host(`portainer-edge.int.zhr.one`)
      - traefik.http.routers.portainer-edge.tls.certresolver=acme
      - traefik.http.routers.portainer-edge.service=portainer-edge
      - traefik.http.services.portainer-edge.loadbalancer.server.port=8000
      - homepage.group=Services
      - homepage.name=Portainer
      # - homepage.icon=emby.png
      - homepage.href=https://portainer.int.zhr.one/
      - homepage.description=Docker UI service

networks:
  traefik:
    name: traefik
    external: true
