version: '3.8'

services:
  attic:
    image: heywoodlh/attic:latest
    restart: always
    volumes:
      - "/data/attic/config:/var/empty/.config/attic"
      - "/data/attic/data:/var/empty/.local/share/attic"
    networks:
      - traefik
    env_file:
      - docker-compose.env
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.attic.entrypoints=websecure
      - traefik.http.routers.attic.rule=Host(`nix.polaris.rest`)
      - traefik.http.routers.attic.tls.certresolver=acme
      - traefik.http.services.attic.loadbalancer.server.port=8080

networks:
  traefik:
    name: traefik
    external: true
