version: '3.8'

services:
  tsgolink:
    image: ghcr.io/tailscale/golink:main
    restart: unless-stopped
    env_file:
      - docker-compose.env
    volumes:
      - /data/tsgolink:/home/nonroot
    labels:
      - com.centurylinklabs.watchtower.enable=true
