version: '3.8'

services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz:latest
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
      start_period: 10s
      interval: 5s
      retries: 5
      timeout: 5s
    volumes:
      - /data/netbootxyz/config:/config
      - /data/netbootxyz/assets:/assets
    networks:
      - traefik
    ports:
      - 69:69/udp
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.netbootxyz.entrypoints=websecure
      - traefik.http.routers.netbootxyz.rule=Host(`netbootxyz.int.zhr.one`, `netbootxyz.int.polaris.rest`)
      - traefik.http.routers.netbootxyz.tls.certresolver=acme
      - traefik.http.services.netbootxyz.loadbalancer.server.port=3000
      - homepage.group=Services
      - homepage.name=Netbootxyz
      # - homepage.icon=emby.png
      - homepage.href=https://netbootxyz.int.zhr.one/
      - homepage.description=LAN Netboot service

networks:
  traefik:
    name: traefik
    external: true
