version: '3.8'
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    # healthcheck:
    #   test: wget --no-verbose --tries=1 --spider http://localhost:8096/health || exit 1
    #   start_period: 10s
    #   interval: 5s
    #   retries: 5
    #   timeout: 5s
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Los_Angeles
    volumes:
      - /data/jellyfin:/config
      - /tmp/transcode:/tmp/transcode
      - tv:/tv:ro
      - movies:/movies:ro
      - books:/books:ro
    networks:
      - jellyfin
      - xteve
      - traefik
      - homepage
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 1900:1900/udp
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.polaris.video`)
      - traefik.http.routers.jellyfin.tls.certresolver=acme
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
volumes:
  movies:
    driver_opts:
      type: nfs
      o: addr=10.10.0.10,nfsvers=4
      device: :/mnt/data/polaris/movies
  tv:
    driver_opts:
      type: nfs
      o: addr=10.10.0.10,nfsvers=4
      device: :/mnt/data/polaris/tv
  books:
    driver_opts:
      type: nfs
      o: addr=10.10.0.10,nfsvers=4
      device: :/mnt/data/content/books

networks:
  traefik:
    name: traefik
    external: true
  homepage:
    name: homepage
    external: true
  xteve:
    name: xteve
    external: true
  jellyfin:
    name: jellyfin
    ipam:
      driver: default
      config:
        - subnet: 172.31.9.0/24
          gateway: 172.31.9.254