version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
      start_period: 10s
      interval: 5s
      retries: 5
      timeout: 5s
    env_file:
      - docker-compose.env
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - pgadmin
      - traefik
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.pgadmin.entrypoints=websecure
      - traefik.http.routers.pgadmin.rule=Host(`pgadmin.int.zhr.one`, `pgadmin.int.polaris.rest`)
      - traefik.http.routers.pgadmin.tls.certresolver=acme
      - traefik.http.services.pgadmin.loadbalancer.server.port=80
      - homepage.group=Database Management
      - homepage.name=PGAdmin
      # - homepage.icon=emby.png
      - homepage.href=https://pgadmin.int.zhr.one/
      - homepage.description=Web UI for Postgres databases

volumes:
  pgadmin:

networks:
  traefik:
    name: traefik
    external: true
  pgadmin:
    name: pgadmin
    ipam:
      driver: default
      config:
        - subnet: 172.25.1.0/24
          gateway: 172.25.1.254