version: '3.8'
services:
  watchtower:
    image: containrrr/watchtower:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - homepage
    env_file:
      - docker-compose.env
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - homepage.group=Infrastructure
      - homepage.name=Watchtower
      - homepage.description=Automatic Docker container updates
      - homepage.widget.type=watchtower
      - homepage.widget.url=http://watchtower-watchtower-1:8080
      - homepage.widget.key=${WATCHTOWER_API_TOKEN}

networks:
  homepage:
    name: homepage
    external: true
